language: go

go:
    - 1.9.x
    - 1.10.x
    - 1.11.x

services:
    - redis-server
    - mysql

install:
    - go get -u golang.org/x/lint/golint
    - go install golang.org/x/lint/golint

script:
    - "sh check.sh"
    - "golint ."
    - go get ./...
    - go test -v ./...

before_install:
  - mysql -e 'CREATE DATABASE golory;'