language: go

go:
    - 1.9.x
    - 1.10.x
    - 1.11.x

services:
    - redis-server
    - mysql
    - postgresql

before_install:
  - mysql -e 'CREATE DATABASE golory;'
  - psql -c 'create database golory;' -U postgres

install:
    - go get -u golang.org/x/lint/golint
    - go install golang.org/x/lint/golint

script:
    - "bash check.sh"
    - "golint ."
    - go get -t ./...
    - go test -v ./...

